//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "CMakeOutputBase.h"


// Declare the bitmap loading function
extern void wxCrafterYlLd9jInitBitmapResources();

static bool bBitmapLoaded = false;


CMakeOutputBase::CMakeOutputBase(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterYlLd9jInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer);
    
    m_notebook = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxBK_BOTTOM);
    
    boxSizer->Add(m_notebook, 1, wxALL|wxEXPAND, 0);
    
    m_panelOut = new wxPanel(m_notebook, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook->AddPage(m_panelOut, _("Output"), false);
    
    wxBoxSizer* boxSizerOut = new wxBoxSizer(wxVERTICAL);
    m_panelOut->SetSizer(boxSizerOut);
    
    m_textCtrlOut = new wxTextCtrl(m_panelOut, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_READONLY|wxTE_MULTILINE);
    wxFont m_textCtrlOutFont = wxSystemSettings::GetFont(wxSYS_SYSTEM_FIXED_FONT);
    m_textCtrlOut->SetFont(m_textCtrlOutFont);
    
    boxSizerOut->Add(m_textCtrlOut, 1, wxALL|wxEXPAND, 0);
    
    m_panelErr = new wxPanel(m_notebook, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook->AddPage(m_panelErr, _("Errors"), false);
    
    wxBoxSizer* boxSizer14 = new wxBoxSizer(wxVERTICAL);
    m_panelErr->SetSizer(boxSizer14);
    
    m_textCtrlErr = new wxTextCtrl(m_panelErr, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_READONLY|wxTE_MULTILINE);
    wxFont m_textCtrlErrFont = wxSystemSettings::GetFont(wxSYS_SYSTEM_FIXED_FONT);
    m_textCtrlErr->SetFont(m_textCtrlErrFont);
    
    boxSizer14->Add(m_textCtrlErr, 1, wxALL|wxEXPAND, 0);
    
    SetMinSize( wxSize(500,200) );
    SetSizeHints(500,300);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    Centre(wxBOTH);
}

CMakeOutputBase::~CMakeOutputBase()
{
}
