//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CMAKEOUTPUT_BASE_CLASSES_H
#define CMAKEOUTPUT_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/imaglist.h>
#include <wx/textctrl.h>

class CMakeOutputBase : public wxPanel
{
protected:
    wxNotebook* m_notebook;
    wxPanel* m_panelOut;
    wxTextCtrl* m_textCtrlOut;
    wxPanel* m_panelErr;
    wxTextCtrl* m_textCtrlErr;

protected:

public:
    CMakeOutputBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~CMakeOutputBase();
};

#endif
