//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CMAKEPLUGIN_BASE_CLASSES_H
#define CMAKEPLUGIN_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/filepicker.h>
#include <wx/statline.h>
#include <wx/button.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/combobox.h>
#include <wx/splitter.h>
#include <wx/listbox.h>

class CMakeHelpPanel;

class CMakeSettingsDialogBase : public wxDialog
{
protected:
    wxStaticText* m_staticTextProgram;
    wxFilePickerCtrl* m_filePickerProgram;
    wxStaticLine* m_staticLine;
    wxStdDialogButtonSizer* m_stdBtnSizer;
    wxButton* m_buttonHelp;
    wxButton* m_buttonOk;
    wxButton* m_buttonCancel;

protected:
    virtual void OnShowHelp(wxCommandEvent& event) { event.Skip(); }

public:
    CMakeSettingsDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("CMakePlugin Settings"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,120), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~CMakeSettingsDialogBase();
};


class CMakeHelpDialogBase : public wxDialog
{
protected:
    wxStaticText* m_staticTextVersion;
    wxStaticText* m_staticTextVersionValue;
    wxNotebook* m_notebook;
    CMakeHelpPanel* m_panelModules;
    CMakeHelpPanel* m_panelCommands;
    CMakeHelpPanel* m_panelProperties;
    CMakeHelpPanel* m_panelVariables;
    wxPanel* m_panelCopyright;
    wxTextCtrl* m_textCtrlCopyright;
    wxStdDialogButtonSizer* m_stdBtnSizer;
    wxButton* m_buttonOk;

protected:

public:
    CMakeHelpDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("CMakePlugin Help"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,400), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~CMakeHelpDialogBase();
};


class CMakeProjectSettingsPanelBase : public wxPanel
{
protected:
    wxCheckBox* m_checkBoxEnable;
    wxStaticText* m_staticTextParent;
    wxChoice* m_choiceParent;
    wxStaticText* m_staticTextSourceDir;
    wxDirPickerCtrl* m_dirPickerSourceDir;
    wxStaticText* m_staticTextBuildDir;
    wxDirPickerCtrl* m_dirPickerBuildDir;
    wxStaticText* m_staticTextGenerator;
    wxComboBox* m_comboBoxGenerator;
    wxStaticText* m_staticTextBuildType;
    wxComboBox* m_comboBoxBuildType;
    wxStaticText* m_staticTextArguments;
    wxTextCtrl* m_textCtrlArguments;

protected:
    virtual void OnCheck(wxUpdateUIEvent& event) { event.Skip(); }
    virtual void OnCheck2(wxUpdateUIEvent& event) { event.Skip(); }

public:
    CMakeProjectSettingsPanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,300), long style = wxTAB_TRAVERSAL);
    virtual ~CMakeProjectSettingsPanelBase();
};


class CMakeHelpPanelBase : public wxPanel
{
protected:
    wxSplitterWindow* m_splitter;
    wxPanel* m_splitterPageList;
    wxListBox* m_listBoxList;
    wxPanel* m_splitterPageText;
    wxTextCtrl* m_textCtrlText;

protected:
    virtual void OnSelect(wxCommandEvent& event) { event.Skip(); }

public:
    CMakeHelpPanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~CMakeHelpPanelBase();
};

#endif
